// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1W9gVFWn40yjIykXqlSbJJs9tnjRebw',
    appId: '1:810901842368:web:c0d604d8c3da1ad9500025',
    messagingSenderId: '810901842368',
    projectId: 'chamcong-1143a',
    authDomain: 'chamcong-1143a.firebaseapp.com',
    storageBucket: 'chamcong-1143a.appspot.com',
    measurementId: 'G-2F9DGWG0HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChFDvv2CO1x2qjKFv2jhJ7OXB9qwIV9XE',
    appId: '1:810901842368:android:9293b9140653a3ad500025',
    messagingSenderId: '810901842368',
    projectId: 'chamcong-1143a',
    storageBucket: 'chamcong-1143a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLvs5skvKZSLpEizltQ-7rajmMgiXqbxk',
    appId: '1:810901842368:ios:10c77bf7c5fa9072500025',
    messagingSenderId: '810901842368',
    projectId: 'chamcong-1143a',
    storageBucket: 'chamcong-1143a.appspot.com',
    iosBundleId: 'com.example.appWorkLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLvs5skvKZSLpEizltQ-7rajmMgiXqbxk',
    appId: '1:810901842368:ios:10c77bf7c5fa9072500025',
    messagingSenderId: '810901842368',
    projectId: 'chamcong-1143a',
    storageBucket: 'chamcong-1143a.appspot.com',
    iosBundleId: 'com.example.appWorkLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU1W9gVFWn40yjIykXqlSbJJs9tnjRebw',
    appId: '1:810901842368:web:4967ee6872dcff7f500025',
    messagingSenderId: '810901842368',
    projectId: 'chamcong-1143a',
    authDomain: 'chamcong-1143a.firebaseapp.com',
    storageBucket: 'chamcong-1143a.appspot.com',
    measurementId: 'G-EZRDG4YWQ6',
  );
}
