part of 'app_pages.dart';

abstract class Routes {
  static const splash = _Paths.splash;
  static const intro = _Paths.intro;
  static const enrollCompany = _Paths.enrollCompany;
  static const setupCompany = _Paths.setupCompany;
  static const getLocation = _Paths.getLocation;
  static const enrollSuccess = _Paths.enroSuccess;
  static const signUp = _Paths.singUp;
  static const createStaff = _Paths.createStaff;
  static const home = _Paths.home;
  static const attendance = _Paths.attendance;
  static const account = _Paths.account;
  static const changePassword = _Paths.changePassword;
  static const leaveRequest = _Paths.leaveRequest;
  static const overtimeRequest = _Paths.overtimeRequest;
  static const login = _Paths.login;
  static const overView = _Paths.overView;
  static const loginSetPassword = _Paths.loginSetPassword;
  static const service = _Paths.service;
  static const serviceDetail = _Paths.serviceDetail;
  static const register = _Paths.regisger;
  static const attendanceManage = _Paths.attendaceManage;
  static const staffManage = _Paths.staffManage;
  static const profileStaff = _Paths.profileStaff;
  static const workingHoursStatistics = _Paths.workingHoursStatistics;
  static const attendanceStaff = _Paths.attendanceStaff;
  static const departmentManage = _Paths.departmentManage;
  static const shiftManage = _Paths.shiftManage;
  static const dashboardStatistics = _Paths.dashboardStatistics;
  static const companyProfile = _Paths.companyProfile;
  static const leaveRequestsManage = _Paths.leaveRequestsManage;
  static const overtimeRequestsManage = _Paths.overtimeRequestsManage;
  static const leaveRequestHistory = _Paths.leaveRequestHistory;
  static const overtimeRequestHistory = _Paths.overtimeRequestHistory;
  static const updateProfile = _Paths.updateProfile;
  static const companySetting = _Paths.companySetting;
  static const companyLocation = _Paths.companyLocation;
  static const language = _Paths.language;
  static const defaultShift = _Paths.defaultShift;
  static const defaultCheckin = _Paths.defaultCheckin;
  static const forgotPassword = _Paths.forgotPassword;
  Routes._();
}

abstract class _Paths {
  static const splash = '/splash';
  static const intro = '/intro';
  static const enrollCompany = '/enroll_company';
  static const setupCompany = '/setup_company';
  static const getLocation = '/get_location';
  static const enroSuccess = '/enroll_success';
  static const singUp = '/sign_up';
  static const createStaff = '/create_staff';
  static const home = '/home';
  static const attendance = '/attendance';
  static const account = '/account';
  static const changePassword = '/change_password';
  static const leaveRequest = '/leave_request';
  static const overtimeRequest = '/overtime_request';
  static const overView = '/overview';
  static const login = '/login';
  static const regisger = '/register';
  static const loginSetPassword = '/login_set_password';
  static const service = '/service';
  static const serviceDetail = '/service_detail';
  static const attendaceManage = '/attendance_manage';
  static const staffManage = '/staff_manage';
  static const profileStaff = '/profile_staff';
  static const workingHoursStatistics = '/working_hours_statistics';
  static const attendanceStaff = '/attendance_staff';
  static const departmentManage = '/department_manage';
  static const shiftManage = '/shift_manage';
  static const dashboardStatistics = '/dashboard_statistics';
  static const companyProfile = '/company_profile';
  static const leaveRequestsManage = '/leave_requests_manage';
  static const overtimeRequestsManage = '/overtime_requests_manage';
  static const leaveRequestHistory = '/leave_request_history';
  static const overtimeRequestHistory = '/overtime_request_history';
  static const updateProfile = '/update_profile';
  static const companySetting = '/company_setting';
  static const companyLocation = '/company_location';
  static const language = '/language';
  static const defaultShift = '/default_shift';
  static const defaultCheckin = '/default_checkin';
  static const forgotPassword = '/forgot_password';
}
